name: Automatic 100 Anime Scraper

on:
  schedule:
    - cron: '0 */6 * * *' # تم التعديل ليعمل كل 6 ساعات فعلياً (0 */6)
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 cloudscraper

      - name: Run Auto Scraper
        env:
          # هذا هو السطر السحري الذي يمرر التوكن من الإعدادات للسكربت
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python scraper.py
